name: all_in_one_converter
description: A comprehensive, feature-rich toolbox app with calculators and converters for everyday use.
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  collection: ^1.17.0
  http: ^1.2.0
  shared_preferences: ^2.3.0
  share_plus: ^10.1.4
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
